version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 831357037758.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t test:$IMAGE_TAG .
      - echo "Listing built Docker images..."
      - docker images
      - echo "Tagging Docker image..."
      - docker tag $IMAGE_TAG 831357037758.dkr.ecr.us-east-2.amazonaws.com/ecr_test_repo:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 831357037758.dkr.ecr.us-east-2.amazonaws.com/ecr_test_repo:$IMAGE_TAG
      - echo "Creating imagedefinitions.json file..."
      - printf '[{"name":"test","imageUri":"831357037758.dkr.ecr.us-east-2.amazonaws.com/ecr_test_repo:%s"}]' $IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

